spring:
  security:
    oauth2:
      client:
        registration:
          chimera-oidc:
            provider: chimera-oidc
            client-id: ${CHIMERA_OIDC_CLIENT_ID}
            client-secret: ${CHIMERA_OIDC_CLIENT_SECRET}
            scope: openid,profile,email
        provider:
          chimera-oidc:
            issuer-uri: ${CHIMERA_OIDC_ISSUER_URI}
